version: "3.3"

services:
  strapi:
    image: strapi/strapi
    container_name: strapi_postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ssps-db
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    container_name: ssps-db
    hostname: ssps-db
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    expose:
      - "5432"
